export const types = {
  ADD_COCKTAILS: '[cocktailReducer] add cocktails list',
  FETCHING_COCKTAILS: '[cocktailReducer] fetching cocktail list',
  ERROR_COCKTAILS: '[cocktailReducer] error fetching cocktail list',
  FETCHING_ACTIVE_COCKTAIL: '[cocktailReducer] fetching active cocktail',
  ADD_COCKTAIL_DETAILS: '[cocktailReducer] add cocktail details',
  ADD_ACTIVE_SEARCH: '[cocktailReduer] add active search',
  ADD_INGREDIENT_ACTIVE: '[ingredientReducer] add active ingredient',
  FETCHING_ACTIVE_INGREDIENT: '[ingredientReducer] fetching active ingredient',
  ADD_RELATED_COCKTAILS: '[ingredientReducer] add related cocktails',
  FETCHING_RELATED_COCKTAILS: '[ingredientReducer] fetching related cocktails',
  LOGIN: '[authReducer] login',
  LOGOUT: '[authReducer] logout',
  FETCHING_LOGIN: '[authReducer] fetching login',
  AUTH_ERROR: '[authReducer] auth error',
  ADD_FAVOURITE: '[userReducer] add favourite',
  REMOVE_FAVOURITE: '[userReducer] remove favourite',
  SET_FAVOURITES: '[userReducer] set favourites',
  FETCHING_FAVOURITES: '[userReducer] fetching favourites'
};